2018-12-09 21:05:34,459 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:18:52,852 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:19:37,713 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:20:37,616 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:21:15,239 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:22:13,945 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:24:29,256 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:29:54,633 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:30:57,933 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:31:06,796 ERROR: Exception on /reset_password_request [POST] [in /Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anthonychen/Documents/practice/Flask/app/routes.py", line 151, in reset_password_request
    send_password_reset_email(user)
  File "/Users/anthonychen/Documents/practice/Flask/app/email.py", line 12, in send_password_reset_email
    send_email('[Microblog] Reset Your Password', sender=app.config['ADMINS'][0], recipients=[user.email],
NameError: name 'send_email' is not defined
2018-12-09 21:31:44,412 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:31:52,170 ERROR: Exception on /reset_password_request [POST] [in /Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anthonychen/Documents/practice/Flask/app/routes.py", line 151, in reset_password_request
    send_password_reset_email(user)
  File "/Users/anthonychen/Documents/practice/Flask/app/email.py", line 12, in send_password_reset_email
    send_email('[Microblog] Reset Your Password', sender=app.config['ADMINS'][0], recipients=[user.email],
NameError: name 'app' is not defined
2018-12-09 21:33:35,371 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
2018-12-09 21:33:46,141 ERROR: Exception on /reset_password_request [POST] [in /Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anthonychen/Documents/practice/Flask/app/routes.py", line 151, in reset_password_request
    send_password_reset_email(user)
  File "/Users/anthonychen/Documents/practice/Flask/app/email.py", line 14, in send_password_reset_email
    text_body = render_template('email/reset_password.txt', user=user, token=token),
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/anthonychen/Documents/practice/Flask/app/templates/email/reset_password.txt", line 4, in top-level template code
    {{ url_for('reset password',token=token,_external=True) }}
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/anthonychen/Documents/practice/Flask/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset password' with values ['token']. Did you mean 'reset_password' instead?
2018-12-09 21:43:15,737 INFO: Microblog startup [in /Users/anthonychen/Documents/practice/Flask/app/__init__.py:52]
